require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/framings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Framing. As you add validations to Framing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Framing.create! valid_attributes
      get framings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      framing = Framing.create! valid_attributes
      get framing_url(framing)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_framing_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      framing = Framing.create! valid_attributes
      get edit_framing_url(framing)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Framing" do
        expect {
          post framings_url, params: { framing: valid_attributes }
        }.to change(Framing, :count).by(1)
      end

      it "redirects to the created framing" do
        post framings_url, params: { framing: valid_attributes }
        expect(response).to redirect_to(framing_url(Framing.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Framing" do
        expect {
          post framings_url, params: { framing: invalid_attributes }
        }.to change(Framing, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post framings_url, params: { framing: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested framing" do
        framing = Framing.create! valid_attributes
        patch framing_url(framing), params: { framing: new_attributes }
        framing.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the framing" do
        framing = Framing.create! valid_attributes
        patch framing_url(framing), params: { framing: new_attributes }
        framing.reload
        expect(response).to redirect_to(framing_url(framing))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        framing = Framing.create! valid_attributes
        patch framing_url(framing), params: { framing: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested framing" do
      framing = Framing.create! valid_attributes
      expect {
        delete framing_url(framing)
      }.to change(Framing, :count).by(-1)
    end

    it "redirects to the framings list" do
      framing = Framing.create! valid_attributes
      delete framing_url(framing)
      expect(response).to redirect_to(framings_url)
    end
  end
end
