require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/schoolings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Schooling. As you add validations to Schooling, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Schooling.create! valid_attributes
      get schoolings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      schooling = Schooling.create! valid_attributes
      get schooling_url(schooling)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_schooling_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      schooling = Schooling.create! valid_attributes
      get edit_schooling_url(schooling)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Schooling" do
        expect {
          post schoolings_url, params: { schooling: valid_attributes }
        }.to change(Schooling, :count).by(1)
      end

      it "redirects to the created schooling" do
        post schoolings_url, params: { schooling: valid_attributes }
        expect(response).to redirect_to(schooling_url(Schooling.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Schooling" do
        expect {
          post schoolings_url, params: { schooling: invalid_attributes }
        }.to change(Schooling, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post schoolings_url, params: { schooling: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested schooling" do
        schooling = Schooling.create! valid_attributes
        patch schooling_url(schooling), params: { schooling: new_attributes }
        schooling.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the schooling" do
        schooling = Schooling.create! valid_attributes
        patch schooling_url(schooling), params: { schooling: new_attributes }
        schooling.reload
        expect(response).to redirect_to(schooling_url(schooling))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        schooling = Schooling.create! valid_attributes
        patch schooling_url(schooling), params: { schooling: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested schooling" do
      schooling = Schooling.create! valid_attributes
      expect {
        delete schooling_url(schooling)
      }.to change(Schooling, :count).by(-1)
    end

    it "redirects to the schoolings list" do
      schooling = Schooling.create! valid_attributes
      delete schooling_url(schooling)
      expect(response).to redirect_to(schoolings_url)
    end
  end
end
