require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subgroups", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Subgroup. As you add validations to Subgroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    #skip("Add a hash of attributes valid for your model")
    {
      acronyms: "F1",
      description: 'Fundamental 1'
    }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Subgroup.create! valid_attributes
      get subgroups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subgroup = Subgroup.create! valid_attributes
      get subgroups_url(subgroup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_subgroup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      subgroup = Subgroup.create! valid_attributes
      get edit_subgroup_url(subgroup)
      expect(response).to be_successful
    end
  end

  describe "POST/create" do
    context "with valid parameters" do
      it "creates a new Subgroup" do
        expect {
          post subgroups_url, params: { subgroup: valid_attributes }
        }.to change(Subgroup, :count).by(1)
      end

      it "redirects to the created subgroup" do
        post subgroups_url, params: { subgroup: valid_attributes }
        expect(response).to redirect_to(subgroup_url(Subgroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Subgroup" do
        expect {
          post subgroups_url, params: { subgroup: invalid_attributes }
        }.to change(Subgroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subgroups_url, params: { subgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subgroup" do
        subgroup = Subgroup.create! valid_attributes
        patch subgroup_url(subgroup), params: { subgroup: new_attributes }
        subgroup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the subgroup" do
        subgroup = Subgroup.create! valid_attributes
        patch subgroup_url(subgroup), params: { subgroup: new_attributes }
        subgroup.reload
        expect(response).to redirect_to(subgroup_url(subgroup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subgroup = Subgroup.create! valid_attributes
        patch subgroup_url(subgroup), params: { subgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subgroup" do
      subgroup = Subgroup.create! valid_attributes
      expect {
        delete subgroup_url(subgroup)
      }.to change(Subgroup, :count).by(-1)
    end

    it "redirects to the subgroups list" do
      subgroup = Subgroup.create! valid_attributes
      delete subgroup_url(subgroup)
      expect(response).to redirect_to(subgroups_url)
    end
  end
end